[package]
name = "align"
version = "1.0.0"
edition = "2021"
authors = ["Khalil Ouali"]
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
term_size = "0.3.2"
align_text = { path = "library/", features = ["clap_arg"] }
