[package]
name = "align_text"
version = "1.0.0"
edition = "2021"
authors = ["Khalil Ouali"]
license = "MIT OR Apache-2.0"
description = "Aligns lines in a block of text within a number of columns."
keywords = ["text", "string", "pretty-print", "format"]

[dependencies]
clap = { version = "4.3.12", optional = true }

[features]
clap_arg = ["clap"]
